apiVersion: v1
kind: Pod
metadata:
  name: pod-hgrabski
spec:
  containers:
  - name: mypod
    image: opensciencegrid/osgvo-docker-pilot:3.6-release
    resources:
      limits:
        memory: 1Gi
        cpu: 1
      requests:
        memory: 100Mi
        cpu: 100m
    command: ["sh", "-c", "sleep 10000"]